//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4GSB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rapport_visite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rapport_visite()
        {
            this.offrirs = new HashSet<offrir>();
        }
    
        public int id_rapport { get; set; }
        public Nullable<int> id_praticien { get; set; }
        public int id_visiteur { get; set; }
        public Nullable<System.DateTime> date_rapport { get; set; }
        public string bilan { get; set; }
        public string motif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<offrir> offrirs { get; set; }
        public virtual praticien praticien { get; set; }
        public virtual visiteur visiteur { get; set; }
    }
}
